### PR TITLE
4.2.x

### PR DESCRIPTION
**Pull request by marsv024**
Update of 4.2.x branch to be in sync of master. Also some 4.2.x fixes.

### CODE REVIEW

**Comment by deas** [comment]
Personally, I am not using 4.2 anywhere. I assume you tried the outcome, right? And things did not get worse than before?

**Comment by marsv024** [comment]
I did not do a full regression test, however I did some testing with the default data lists and its configuration and it seemed to work fine.

**Comment by deas** [comment]
Again, thanks @marsv024 . Let's pray the merge did not introduce to many regressions. ;) Maybe @douglascrp feels brave enough to try it out in case he still has 4.2 running somewhere.

**Comment by douglascrp** [comment]
@deas I still use it in a production server, but I couldn't even look at the changes you have been doing.
I'll do so in the next time I work on that server.

**Comment by deas** [comment]
@douglascrp I guess it's just way to much to review. Just pray and try it out. At least it seems to work for @marsv024 .

**Comment by douglascrp** [comment]
@deas It's not something hard to test. The problem is that I have to restablish my dev server, and then deploy the new version.
Problem is always time.
I'll let you both know the result.

**Pull request merged**
